# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
 stripe_api_key: sk_test_eZV9ikJF9SCsk3dNFE1OJJdN
 stripe_publishable_key: pk_test_mO0PZXWMnY2F921I3t6oMkZl
#
production:
 stripe_api_key: sk_live_ZjxYi4pEiPa73F026Dheq29v
 stripe_publishable_key: pk_live_2DO4JZTgq6GgB5yy9mpYMZ1k
